social_login-mysql:
  container_name: social_login-mysql
  image: mysql:5.7.9
  # volumes:
  #   - ~/volumes/jhipster/social_login/mysql/:/var/lib/mysql/
  environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=social_login
  ports:
    - "3306:3306"
  command: mysqld --lower_case_table_names=1
